;Same as Resourse.rc

;Menu
IDM_MAIN		equ    	1000
IDM_OPEN		equ    	1101
IDM_SAVE		equ    	1102
IDM_NEW			equ		1104
IDM_UNDO		equ		1206
IDM_VERSION		equ		1201
IDM_FLIPH		equ		1121
IDM_FLIPV		equ		1122
IDM_CLEAR		equ		1129
IDM_CSIZE		equ		1130
IDM_ROTATION	equ		1131
IDM_PEN         equ		1132
IDM_BRUSH       equ		1133
IDM_TEXT        equ		1134
IDM_SELECTAREA  equ		1135
IDM_ERASER      equ		1136
IDM_OILPAINT    equ		1137
IDM_SELECTCOLOR equ		1138
IDM_PAINTCOLOR  equ		1139
IDM_PENSIZE     equ		1140
IDM_PENTYPE     equ		1145
IDM_LINE        equ		1142
IDM_ELLIPSE     equ		1144
IDM_BRUSHTYPE   equ		1141
IDM_RECTANGLE   equ		1150
IDM_CUSTOM   	equ		1151
IDM_POLYGON   	equ		1152
IDM_POLYLINE   	equ		1153
IDM_ARC     	equ		1154

;Accelerator
IDA_MAIN		equ 	2000

;StatusBar
ID_STATUSBAR    equ 	3000

;Dialog
IDD_COLORDIALOG		equ 	103
IDC_COLORBOX		equ 	100
IDC_COLORLABEL 		equ 	-1

IDD_WIDTHDIALOG		equ		104
IDC_WIDTHLABEL 		equ 	-2
IDC_WIDTHBOX        equ     101

IDD_STYLEDIALOG		equ		105
IDC_STYLELABEL 		equ		-3
IDC_STYLEBOX        equ 	102

IDD_BRSTYLEDIALOG	equ		106
IDC_BRSTYLELABEL 	equ		-4
IDC_BRSTYLEBOX      equ 	103

IDD_TEXTDIALOG		equ		110
IDC_TEXTLABEL 		equ		-5
IDC_TEXTBOX      	equ 	108

IDD_ROTATEDIALOG    equ		111
IDC_ROTATELABEL     equ		-6
IDC_ROTATEBOX       equ		109 

IDD_SETSIZEDIALOG   equ		112
IDC_SETWIDTHLABEL   equ		-7
IDC_SETHEIGHTLABEL  equ		-8
IDC_SETWIDTH        equ		110
IDC_SETHEIGHT       equ		111

IDD_POLYGONDIALOG   equ		113
IDC_POLYGONLABEL    equ		-9
IDC_POLYGONBOX      equ		112   

IDD_POLYLINEDIALOG   equ	114
IDC_POLYLINELABEL    equ	-10
IDC_POLYLINEBOX      equ	113

IDD_ARCDIALOG        equ    115
IDC_RADIUSLABEL      equ    -11
IDC_STARTALABEL      equ    -12
IDC_SWEEPALABEL      equ    -13
IDC_RADIUSBOX        equ    114
IDC_STARTABOX        equ    115
IDC_SWEEPABOX        equ    116 

;Cursor
IDC_BRUSH        equ     101
IDC_TEXT         equ     102
IDC_ERASER       equ     103
IDC_STRAW      equ       104
IDC_BUCKET      equ       105
